### ISSUE TITLE
How to add a search cancel button?

### ISSUE THREAD

**Issue by svetlanapuro** [algolia/algoliasearch-jekyll#13]
Hi there,

I'm using Algolia search for my Jekyll site. And I would like to add a cancel button as soon as a user starts typing text in a search field. Is there any way to do it? I would really appreciate your help.

**Comment by pixelastic** [comment]
Hello @iloveip,

This is totally possible, and could be achieved with a bit of JavaScript. The way I would do it is:
- listen to the `keyup` event in the input
- if the input is not empty, display a "Cancel" button, and hide it when the input is empty
- when the cancel button is clicked, clear the input

You can have a look at how [we did it in our Hyde example](https://github.com/algolia/algoliasearch-jekyll-hyde/blob/master/public/js/algolia.js). Also note that we recently released our [autocomplete.js](https://github.com/algolia/autocomplete.js) library that make part of the work easier (it is a replacement of typeahead)

**Comment by svetlanapuro** [comment]
@pixelastic Thank you very much for your reply!

But I still have some difficulties, as I'm just learning JavaScript. To display and hide a cancel button I've written the following code:

```
$('.js-algolia__input').keyup(function() {
  if (!$('.js-algolia__input').val().trim()=="") {
    $('.search-cancel').addClass('is-visible');
  } else {
    $('.search-cancel').removeClass('is-visible');
  };
});
```

How can I clear the input when the cancel button is clicked? Is it also done with JavaScript?

I would really appreciate your help.

**Comment by pixelastic** [comment]
As a general good practice, I would first extract the `$('.js-algolia__input')` and `$('.search-cancel')` into variables as you're using them several times. This will prevent jQuery from re-finding them in the DOM everytime.

I would also suggest to have a look at the jQuery `toggleClass()` method that could simplify your code. Other than that, your code seems ok.

To clear the input when the button is clicked, yes, you'll also need JavaScript. You can call `.click()` on the button, and passing it a function that will change the input value (using `.val()`).

This should get you on the right track :)

Happy coding

**Comment by svetlanapuro** [comment]
@pixelastic Thank you very much for your help! :) I ended up having the following code, may be someone will need it too:

```
// Initiate search cancel button
var $searchCancel = $('.search-cancel');
$searchInput.keyup(function() {
  if (!$searchInput.val().trim()=="") {
    $searchCancel.addClass('is-visible');
  } else {
    $searchCancel.removeClass('is-visible');
  };
});

// Clear search input when search cancel button is clicked
$searchCancel.click(function() {
  $searchInput.val('');
  $searchCancel.removeClass('is-visible');
  hideResults();
});
```

There already was a variable for `$('.js-algolia__input')`, so I just added a variable for `$('.search-cancel');`. I will look into `toggleClass()` more. But as for now I couldn't get it to work, because it was simply hiding and showing the cancel button with each new key press.
