### ISSUE TITLE
no implicit conversion of nil into Hash

### ISSUE THREAD

**Issue by borisschapira** [algolia/algoliasearch-jekyll#17]
| jekyll | algoliasearch-jekyll |
| --- | --- |
| 3.0.1 | 0.5.3 |

First, thank you for your hard work on this plugin. It's very much appreciated. Now, for the bug...

The command :

```
bundle exec jekyll algolia push
```

produces the error : 

```
jekyll 3.0.1 | Error:  no implicit conversion of nil into Hash
```

Even if with `--verbose`mode, I can't manage to produce more info, sorry.

**Comment by pixelastic** [comment]
Thanks for the report @borisschapira :)

Jekyll 3.0 is not currently supported by the plugin. I plan on supporting it, but haven't yet found the time to fix all the issues. I think this is related to #14.

**Comment by pixelastic** [comment]
Hello @borisschapira,

I've worked on the compatibility with Jekyll v3.0, but I never encountered this issue so I cannot reproduce.

Do you have some code available (a public repo maybe), that I could use to try to reproduce on my end?

**Comment by borisschapira** [comment]
I've juste update the plugin an tried again. I have the message again, just after the beginning of the first extraction :

``` bash
[…]
Rendering Markup: /26/index.html
Rendering Layout: 26/index.html
Rendering Layout: 26/index.html
Post-Render Hooks: /26/index.html
Extracting data from 404.html
jekyll 3.0.1 | Error:  no implicit conversion of nil into Hash
```

**Comment by pixelastic** [comment]
Did you try with the `fix/jekyll-v3` branch? I haven't released it on Rubygems yet.

Without more info I'm afraid I won't be able to fix it. Are you using other plugins? Do you have files with empty front matter headers (the part between `---`)?

**Comment by borisschapira** [comment]
I've just tried with this branch using this syntax in Gemfile :

```
gem 'algoliasearch-jekyll', :github => 'algolia/algoliasearch-jekyll', :branch => 'fix/jekyll-v3'
```

but I've got the same error message. I tried removing the 404.md file (preventing the compilation to render 404.html) but now the same error is happening on about.html, and so on and so on. I'm so sorry that there is no stacktrace in verbose mode :sad:…

**Comment by borisschapira** [comment]
As for the other plugins I use : https://github.com/borisschapira/jekyll/blob/master/Gemfile

**Comment by pixelastic** [comment]
I cloned your repo and tried to `bundle install` but I got a compilation (!) error about ImageMagick. So I commented out the `jekyll-responsive-image` plugin. `bundle install` worked correctly, but I then had an issue with a bad symlink between `./assets/images` and `_posts/images`. So I stopped investigating :)

I think the issue comes from one of the others plugins that might interfere with this one. I had the issue in the past with a plugin enhancing the tags. Do you think you could create a smaller test case, stripping the `Gemfile` of as many plugins as possible and still reproducing the issue?

**Comment by borisschapira** [comment]
Sorry, I did not do what was needed to easily test this repo (I just wanted to share my config). That's corrected but doing so, I detecter... a simple configuration mistake in the configuration (spaces were missing in the algolia configuration). Now, that's ok.

And tada ! Your branch `fix/jekyll-v3` works very well and my content was pushed.
Next move : incremental push. Good luck :+1:
