### ISSUE TITLE
No subcommand "algolia"

### ISSUE THREAD

**Issue by faichelbaum** [algolia/algoliasearch-jekyll#24]
Hi

I followed the procedure from the readme (including the Gemfile, bundle install, ...) but when running jekyll help, I can't find the algolia subcommand

Any idea how to debug this ?

**Comment by faichelbaum** [comment]
Ok I found the issue.

In the Gemfile, I use to put the "gem 'algoliasearch-jekyll'" as a regular gem whereas I needed to add :

group :jekyll_plugins do
  gem 'algoliasearch-jekyll'
end

**Comment by pixelastic** [comment]
Yes, it needs to be in the `:jekyll_plugins` group to be correctly catched by Jekyll. Glad you found the solution :)
