### ISSUE TITLE
Add the collection name in the index

### ISSUE THREAD

**Issue by ThibautGery** [algolia/algoliasearch-jekyll#25]
Is it possible to index the [collection](https://jekyllrb.com/docs/collections/) name like `my_collection` in the documentation exemple ?

**Comment by pixelastic** [comment]
Not sure I get what you mean. Could you give me an example of the collection files, and the data you would like to index?

**Comment by ThibautGery** [comment]
On my [project](https://github.com/sgmap/api.gouv.fr/blob/gh-pages/_config.yml), I want to create facet on my different collections: `reutilisation` and `api`. I would love to have an attribute (for example, named `collection_name` with either `reutilisation` or `api`). For now I'm using a custom default variable `layout` in my case

**Comment by pixelastic** [comment]
Everything that you put in the front-matter (header of the file, between the `---`), will be pushed to the record. You can add your own if you want as a workaround.

I'll add support for this feature in one of the next versions, I'm working on releasing the v1 with a few improvements.

**Comment by pixelastic** [comment]
Fixed in the `v1` branch
