### ISSUE TITLE
algoliasearch not registering as a jekyll subcommand

### ISSUE THREAD

**Issue by andrewmkrug** [algolia/algoliasearch-jekyll#26]
jekyll 3.1.1 and octopress 3.0.11 (not sure if this affects anything)

I followed the steps outlined in the readme however when running  `jekyll --help` the algolia sub command is not listed. 

Are there any troubleshooting steps to help with diagnosis or fixing this?

**Comment by pixelastic** [comment]
Did you put the plugin in the `:jekyll_plugins` group in your `Gemfile`? That's how Jekyll knows that new subcommands are added.

``` ruby
group :jekyll_plugins do
  gem 'algoliasearch-jekyll', '~> 0.7.0'
end
```

**Comment by andrewmkrug** [comment]
yes i did to that, any other suggestions?

**Comment by pixelastic** [comment]
Would you have a repository where I could reproduce the issue? Or at the very least a copy of your `Gemfile`?

**Comment by andrewmkrug** [comment]
```
source 'https://rubygems.org'

ruby '2.3.1'

gem 'jekyll', '~> 2.5.3'

group :jekyll_plugins do
    gem 'jekyll-compose'
    gem 'jekyll-paginate'
    gem 'algoliasearch-jekyll', '~> 0.7.0'
    gem 'octopress-paginate'
    gem 'octopress', '~> 3.0'
    gem 'jekyll-paginate'
end
```

**Comment by pixelastic** [comment]
Could you try pulling this branch https://github.com/algolia/algoliasearch-jekyll-hyde/tree/issue/command-not-found and run `bundle install` then `jekyll -h` and copy-paste the output?

I put your `Gemfile` in this test repository, and everything is working fine on my side.

**Comment by andrewmkrug** [comment]
Bundle complete! 6 Gemfile dependencies, 50 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Andrews-MBP-2:algoliasearch-jekyll-hyde-issue-command-not-found andrew$ jekyll -h
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
jekyll 3.1.1 -- Jekyll is a blog-aware, static site generator in Ruby

Usage:

  jekyll <subcommand> [options]

Options:
        -s, --source [DIR]  Source directory (defaults to ./)
        -d, --destination [DIR]  Destination directory (defaults to ./_site)
            --safe         Safe mode (defaults to false)
        -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
            --layouts DIR  Layouts directory (defaults to ./_layouts)
            --profile      Generate a Liquid rendering profile
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs

Subcommands:
  docs
  import
  build, b              Build your site
  clean                 Clean the site (removes site output and metadata file) without building.
  doctor, hyde          Search site and print specific deprecation warnings
  help                  Show the help message, optionally for a given subcommand.
  new                   Creates a new Jekyll site scaffold in PATH
  serve, server, s      Serve your site locally

**Comment by andrewmkrug** [comment]
While troubleshooting a different issue with `jekyll-paginate` I came across this command from apost saying that there is something weird with my ruby env, but the algolia command is now showing up. There was another post saying that it might be caused by different versions of jekyll being installed

`bundle exec jekyll`

**Comment by pixelastic** [comment]
Oh right. I made the assumption that you were using `rvm` to handle your various Ruby versions. `rvm` also automatically prefix the `bundle exec` to any command it knows.

I think if you go with `bundle exec jekyll -h` you should have `algolia` displayed as a command. Could you confirm?

**Comment by andrewmkrug** [comment]
i thought i was using rvm, apparently not though, new laptop setup sometimes takes a while, thanks though, I do have the algolia subcommand showing up

**Comment by pixelastic** [comment]
Great, glad you managed to fix it :)
