### ISSUE TITLE
Errors: Make a more explicit error message for big records

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-jekyll#28]
When currently trying to push a record over the limit, the user is greeted with

```
Algolia Error: HTTP Error
Cannot POST to https://APPID.algolia.net/1/indexes/index_tmp/batch: {"message":"Record is too big size=123992 bytes. Contact us if you need an extended quota","status":400} (400)
```

Could be nice to catch the error and provide an explanation and work-arounds.

**Comment by pixelastic** [comment]
This is fixed in the `v1` branch

**Comment by Haroenv** [comment]
this is a great error message, wish it was visible to users already 😂, see #59 for someone recently having this error
