### ISSUE TITLE
add option to pick index_name, application_id from environment variables

### ISSUE THREAD

**Issue by akshaykmr** [algolia/algoliasearch-jekyll#29]
Would it be possible to have these settings picked up from environment variables (optional if not found in config.yml). This is to switch the index to which the records are to be pushed based on these values, rather than having it fixed in config.yml.
Thanks.

**Comment by pixelastic** [comment]
Great idea. I'll add that on the v1 roadmap

**Comment by pixelastic** [comment]
This has been added in the v1 branch.

**Comment by akshaykmr** [comment]
Thanks! Is there anyway I can use it now? We need this to work asap.

**Comment by pixelastic** [comment]
I've just ported it to master. You should be able to try version 0.8.0.

Just define `ALGOLIA_INDEX_NAME` and `ALGOLIA_APPLICATION_ID` as environment variables and they will be used instead of the values in `_config.yml`.

Tell me if this works for you.

**Comment by akshaykmr** [comment]
Working, thanks for quick response :)
