### ISSUE TITLE
Renaming plugin to jekyll-algolia

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-jekyll#31]
The [Jekyll Style Guide](http://ben.balter.com/jekyll-style-guide/) mention that plugins should be prefixed with `jekyll-`.

I'm not sure how "official" this styleguide is, but it seems to be the only one existing.

**Comment by pixelastic** [comment]
- [x] The plugin should be renamed to `jekyll-algolia` instead of `algoliasearch-jekyll`. 
- [x] See if I can rename gems or if I'll need to create a new one
- [ ] ~~New class should be in `Jekyll::JekyllAlgolia` (because I'm monkey-patching stuff)~~

**Comment by nhoizey** [comment]
On the same topic: https://github.com/jekyll/jekyll-admin/issues/25

**Comment by pixelastic** [comment]
So it's not possible to rename a gem. What I can do instead (and what I did with the `html-hierarchy-extractor` dependency) is to create a new gem and continue development there, while freezing development on the previous gem.

I still add one last release to the previous version that adds deprecation warnings telling everyone to upgrade to the new gem.

**Comment by pixelastic** [comment]
To sum up:

New gem will be named `jekyll-algolia` because that's the standard in the Jekyll world. 

Jekyll will try to import it automatically by doing `require 'jekyll-algolia'` so will have my code available in `lib/jekyll-algolia.rb`. Rubocop will complain (filename should use `_`, not `-`), but I'll make an exception for this one.

Then the code will extend `Jekyll::Algolia`, from where I'll be able to monkey-patch the `build` method.

I've already started development of the new `jekyll-algolia` gem (still in a private repo for now, to avoid any confusion). When it will be released, I'll release directly with a `v1` and will mark this repo as deprecated.

**Comment by DirtyF** [comment]
```yaml
Naming/FileName:
  Exclude:
    - lib/jekyll-algolia.rb
```

should do the trick for Rubocop ✅

**Comment by pixelastic** [comment]
The new repo is open: https://github.com/algolia/jekyll-algolia

It is not released on RubyGems yet, you still have to manually clone it to use it. This officially starts the beta-test phase ;)
