### ISSUE TITLE
HTTP error: cannot reach any host : execution expired

### ISSUE THREAD

**Issue by akshaykmr** [algolia/algoliasearch-jekyll#32]
`bundle execute jekyll algolia push` returns the following error inside vagrant 

```
[vagrant@vagrant-0-7-0 portal]$ bundle exec jekyll algolia push
Configuration file: /Test/portal/_config.yml
Algolia Error: HTTP Error
Cannot reach any host: execution expired, execution expired, execution expired, execution expired
```

**Comment by akshaykmr** [comment]
I pinged the servers it would call normally from within vagrant and all of them seem to respond quickly.  

```
--- c1-in-1.algolianet.com ping statistics ---
13 packets transmitted, 13 received, 0% packet loss, time 16501ms
rtt min/avg/max/mdev = 5.973/7.472/8.246/0.674 ms
```

Any insight on what might be causing this error? I don't think its related to vagrant. using version 0.8.0 Thanks

**Comment by pixelastic** [comment]
Could you try to ping (from inside Vagrant) the following hosts:
- {APPID}-dsn.algolia.net
- {APPID}.algolia.net

With `{APPID}` being the `application_id` defined in your `_config.yml`. Also, could you share this APPID here so I can have a look as well?

**Comment by pixelastic** [comment]
ping @akshayKMR

**Comment by akshaykmr** [comment]
Whoops sorry for late response. It was a DNS issue with our vagrant box. Had to edit `/etc/resolv.conf`. Thanks

**Comment by pixelastic** [comment]
Glad to hear you resolved it :)

**Comment by carlead** [comment]
@akshayKMR Can you explain which modifications you made to your file /etc/resolv.conf ? Thanks

**Comment by akshaykmr** [comment]
@carlead  The `resolv.conf` file contains nameservers used for dns. They are used in order they are listed. Our organization vagrant box had two entries, I simply moved the second one to the top and it started working.

**Comment by carlead** [comment]
@akshayKMR Ok thank you, I'll give it a try !
