### ISSUE TITLE
Search isn't responsive on mobile

### ISSUE THREAD

**Issue by copycatchiller** [algolia/algoliasearch-jekyll#33]
The search bar doesn't work on mobile. Well, it works, but you have to manually click out. Enter doesn't close the keyboard and so it makes the interaction really awful.

**Comment by pixelastic** [comment]
Hello @danielms215,

This plugin only takes care of the indexing part, not the UI. Could you give me the link of the website where you saw this issue?

**Comment by copycatchiller** [comment]
I see!
The website is [here.](http://shoulditakethecredit.com/faq)

**Comment by pixelastic** [comment]
May I ask you to submit the issue on our [Hyde fork](https://github.com/algolia/algoliasearch-jekyll-hyde/issues) instead?

I'll rework on the theme in the near future to make it compatible with the upcoming v1 of the plugin, I'll try to enhance the mobile navigation at the same time. Don't hesitate to post a link to the website, the issue and what you would think would be better, this will help me fix it :)
