### ISSUE TITLE
Feature Request: Add ability to push to any index

### ISSUE THREAD

**Issue by akshaykmr** [algolia/algoliasearch-jekyll#37]
Currently one can only push to a single index, set in configuration. This works well if generated indices are similar in nature. However there are some limitations as when the indices are different in content,  one cannot leverage multiple sources in autocomplete.js for better styling and separation.

Not sure of the best way to implement it. Maybe let the user set a specific key in return `item` from custom hook which decides the destination index. 
Thanks

**Comment by pixelastic** [comment]
Interesting idea. Just to be sure I understand it correctly, you would like, for example to push all your `posts` to a `posts` index and your `pages` to a `pages` index? With the name of the index being of your chosing of course.

Would it be possible for you to achieve the same effect by using facets? In this example defining the `type` (`page`/`post`) as a facet and using two different sources in `autocomplete.js`, both targetting the same index, but with different facet filters?

**Comment by pixelastic** [comment]
Ping @akshayKMR, did you give a go at my suggested workaround?

**Comment by akshaykmr** [comment]
I'm currently not working on that project. But I'm sure what you suggest will achieve the same effect, ideally though some would prefer to keep indices separate eg. an index for movies and another for actors etc. i.e when the content is largely different.

**Comment by pixelastic** [comment]
I'm closing this issue. You raised a very valid point, but I don't think I will fix it with allowing to specify indices. I've opened a follow-up issue in the new repo: https://github.com/algolia/jekyll-algolia/issues/9

I think this issue can be solved with documentation and live-examples and will work on that.

Thanks for the feedback!
