### ISSUE TITLE
Possibility to dissociate build and push

### ISSUE THREAD

**Issue by borisschapira** [algolia/algoliasearch-jekyll#39]
Hi!

I use a CI process for my Jekyll website with a double test gate:
1. I test my blog posts (in fact, a script verifies that all Front Matter are valid YAML)
2. I build my website
3. I test the result with html-proofer
4. If everything is good, I push the _site directory to Production and index the content in Algolia

As my building and indexing phases are separate, my CI process is very long because in order to index, the plugin re-build the website. I know that there is a way to tell the plugin to build the index (hence, the website) without pushing. Is there a way to tell the plugin to push the index without re-building, assuming the previous index is in cache?

**Comment by redox** [comment]
Hi @borisschapira,

from what I [remember](https://github.com/algolia/algoliasearch-jekyll/blob/master/lib/push.rb#L82-L96), we use the regular build workflow and are just replacing the final `write` step to push to Algolia. So that won't be possible as-is. @pixelastic will need to confirm, but he is current enjoying a bit of ☀️ 🌅 🌴  and will be back in 2 weeks 👍

**Comment by borisschapira** [comment]
So I expect he will not answer until then, there is no rush and the mojitos can't wait! 😄

**Comment by pixelastic** [comment]
Hey @borisschapira,

I understand the pain it is to have a long build process on CI... But as @redox was saying, the plugin monkey patches the internal `write` method that is normally used by Jekyll for writing HTML files on disk. In other words, it does not read the generated HTML files to build the index, it actually _replace_ the writing of HTML files on disk with the building of the index.

This is a deep internal part of how the plugin is working and I don't see any way to change it that won't involve a massive rewriting of the plugin. I'm afraid there is not much I can do for you here.
