### ISSUE TITLE
Enhancement: Using the new facetingAfterDistinct=true for correct facet count

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-jekyll#40]
The API now accept an `facetingAfterDistinct=true` that does the count of facets after the `distinct` (default is to do it before). Without this option, the count for facets when doing a distinct was "wrong" (ie. it did not take the distinct into account, returning way higher count that what was visible).

This option allow to fix this issue, but come with a performance counterpart on big indices. I think it's safe to set it as default for Jekyll blogs.

**Comment by rayrutjes** [comment]
You should wait just a bit, because we currently have an issue with the feature when the query is empty ;)

**Comment by pixelastic** [comment]
Also, the feature is query-time only so its place should not be in the plugin code, but in the front-end examples.

**Comment by pixelastic** [comment]
Issue moved to new repo: https://github.com/algolia/jekyll-algolia/issues/10
