### ISSUE TITLE
Status of V1

### ISSUE THREAD

**Issue by keybits** [algolia/algoliasearch-jekyll#45]
@pixelastic we're about to set up this plugin for a new docs site. Should we use V1 branch? Are you planning to start updating it again soon?

Thank you for your work on this.

**Comment by pixelastic** [comment]
Hello @keybits,

v1 is working, as far as I can tell. It's fully tested, compatible with Jekyll 2 and 3, but I'm the only one that ever used it in production. As it's not officially released, it's not yet officially supported by Algolia.

Thanks for bringing this back to my attention, I'm checking with the rest of the team to take some decision about what to do with this plugin. We don't feel it would be fair to officially release it if we cannot provide a fair amount of support on it and iron out the last bugs discovered after release.

**Comment by svetlanapuro** [comment]
Hi there,
Do you have any updates on v1?

**Comment by DirtyF** [comment]
Usually the proper response is: when it's finished :)

**Comment by svetlanapuro** [comment]
@DirtyF Yes, I understand :) But I have a particular problem, which I described here #38, and I can not update my search index. That's why I'm asking.

**Comment by pixelastic** [comment]
I'd love to be able to give you more news, but so far it hasn't moved. I still want to resurect it, but still don't have an ETA. Sorry I can't tell you more :/

**Comment by johlym** [comment]
For what it's worth, we pulled the repo and built the gem using the v1 branch for the `lazy_update` logic and it's been working great. YMMV, of course, but if that's the only reason you want to use v1, it seems fine.

**Comment by pixelastic** [comment]
Thanks for the info. I'm going to dive deep into the last remaining bugs in the coming weeks in order to officially release the v1 branch. Release is coming :)
