### ISSUE TITLE
algolia selector returning undefined

### ISSUE THREAD

**Issue by lingxz** [algolia/algoliasearch-jekyll#48]
Hi, I'm using Algolia search for my blog, and for some reason the algolia selector is always returning undefined, and I can't seem to figure out why. The site is [here](https://theconfused.me) and the source code is [here](https://github.com/lingxz/lingxz.github.io). I'm using the js from jekyll-algolia-hyde with a slight modification. Thanks!

**Comment by Haroenv** [comment]
I think there’s a small mistake in the html for your input, I made a PR to your repository: https://github.com/lingxz/lingxz.github.io/pull/15

**Comment by lingxz** [comment]
thanks @Haroenv! but the issue still persists, apparently.

**Comment by pixelastic** [comment]
Hey @lingxz, could you give me a link to the file that contains the `undefined` selector? I have trouble finding the relevant one in your repo :)

**Comment by lingxz** [comment]
hi @pixelastic, the relevant algolia files are [here](https://github.com/lingxz/lingxz.github.io/blob/781da2d7080374b43f0ca65cae751d81b3939eb3/_includes/algoliasearch.html#L12) and [here](https://github.com/lingxz/lingxz.github.io/blob/b0148d18e61c7a0e0ede92751af1ac40b64df4ca/assets/js/algoliasearch.js), and the search box is [here](https://github.com/lingxz/lingxz.github.io/blob/master/_pages/search.html#L10). The undefined selector appears when the search result is returned. For example, searching for something like "test" in the search box and clicking enter returns some links, and the links go something along the lines of `https://theconfused.me/blog/drifter-writing-interactive-fiction-with-ink/#algolia:undefined`

**Comment by lingxz** [comment]
Ah, it seems that when using v1, the css_selector property is not indexed properly. When using v1, the css_selector shows as null but when I revert back to using the released 0.8 version, all is working well.

**Comment by pixelastic** [comment]
If you're using the `v1`, the key is actually named `record_css_selector` there. Note that `v1` is not (yet) officially released. You should be able to find all the relevant configuration options and documentation [here](https://github.com/algolia/algoliasearch-jekyll/tree/v1).

I'm closing the issue as it seems to fix your issue. If not, feel free to comment and I'll re-open it.
