### ISSUE TITLE
Update nokogiri dependency to version 1.7.2 or higher

### ISSUE THREAD

**Issue by nhoizey** [algolia/algoliasearch-jekyll#54]
There is a vulnerability in nokogiri versions < 1.7.2: https://snyk.io/vuln/SNYK-RUBY-NOKOGIRI-20367

**Comment by redox** [comment]
Thanks for spotting that, on it!

**Comment by nhoizey** [comment]
Thanks!

**Comment by redox** [comment]
Released in 0.8.1
