### ISSUE TITLE
Cannot install algoliasearch-jekyll

### ISSUE THREAD

**Issue by theahmadzai** [algolia/algoliasearch-jekyll#59]
Getting an error when installing "algoliasearch-jekyll"

**Ruby 2.3
Jekyll 3.5**
------------
`gem install algoliasearch-jekyll` is causing this error

```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (scripts/./watch_v2, D:/ruby/lib/ruby/gems/2.3.0/gems/algoliasearch-jekyll-0.8.2/scripts/watch)

```

when running bundle install and adding `algoliasearch-jekyll` to Gemfile also not working

My Gemfile

```ruby
source 'https://rubygems.org'

gem 'github-pages'

group :jekyll_plugins do
    gem 'algoliasearch-jekyll', '~> 0.8.2'
    gem 'jekyll-paginate'
    gem 'jekyll-seo-tag'
    gem 'jekyll-feed'
end

gem 'wdm', '>= 0.1.1' if Gem.win_platform?
```

Also deleted the gemfile.lock then ran bundle install still won't work

**Comment by Haroenv** [comment]
I think that this is related to issues like these: https://stackoverflow.com/a/17552710/3185307, did you try those solutions?

**Comment by theahmadzai** [comment]
Worked ran command window as administrator :)

**Comment by theahmadzai** [comment]
Another issue appeared 

```
$ ALGOLIA_API_KEY='XXX' jekyll algolia push
Configuration file: D:/www/durableblog/website/_config.yml
  Indexing 47 items
Algolia Error: HTTP Error
Cannot POST to https://6WGYCY2OL1-2.algolianet.com/1/indexes/durableblog_tmp/batch: {"message":"Record at the position 43 is too big size=16366 bytes. Contact us if you need an extended quota","position":43,"status":400} (400)
```

my config in config.yml is 

```ruby
algolia:
  application_id: '.....'
  index_name: '.....'
```

is there anything else to set?

**Comment by Haroenv** [comment]
Hey @theahmadzai, you just posted your private API key on a public forum. I edited your message, but you better revoke this key and generate a new one. 

As for your issue, it's because your record is bigger than 10kb, you can split it up with the instructions in the error message [here](https://github.com/algolia/algoliasearch-jekyll/blob/dcfb1529eab0278da9fac8e1d39eb3d93eb552ec/txt/record_too_big)

Have a nice day!

**Comment by theahmadzai** [comment]
Oh lol.. 
Thanks, I revoked it anyways I solved everything thanks.

**Comment by Haroenv** [comment]
perfect @theahmadzai
