### ISSUE TITLE
jekyll algolia push command is not working

### ISSUE THREAD

**Issue by svetlanapuro** [algolia/algoliasearch-jekyll#9]
Hi there,

I followed your instructions and installed Jekyll Algolia as a gem. But when I try to run `$ jekyll algolia push`, I get an error:

```
MacBook-Pro-Svetlana:iloveip svetlana$ jekyll algolia push
Invalid command. Use --help for more information 
```

How can I fix that?

**Comment by borisschapira** [comment]
Hello @iloveip : is the simple "jekyll" command available ? If not, you have a problem with jekyll, not algolia. Maybe the folder of your gems is not in your path ?

**Comment by svetlanapuro** [comment]
@borisschapira `jekyll` command is available.

**Comment by redox** [comment]
@iloveip are you using a `Gemfile` for your project or did you install the `algoliasearch-jekyll` gem globally? (it requires a `Gemfile`).

Could you also try to run `bundle exec jekyll algolia push` instead of just `jekyll algolia push`?

Also, maybe you need to explicitly add the gem to your `_config.yml` file, like https://github.com/algolia/bootstrap/blob/algolia-search-v4/_config.yml#L21-L23

**Comment by pixelastic** [comment]
You need to add the gem to your Gemfile, wrapped in a `group :jekyll_plugins`, and add it to the `gems` configuration option of your `_config.yml`

``` ruby
# Gemfile
group :jekyll_plugins do
  gem 'algoliasearch-jekyll', '~> 0.4.3'
end
```

``` yaml
# _config.yml
gems:
  - algoliasearch-jekyll
```

An easy way to test if things are working is simply to call `jekyll` (or `bundle exec jekyll` if you do not have the `bundle` auto-hooks installed). It should display the list of available `jekyll` commands, and `algolia` should be displayed last

**Comment by svetlanapuro** [comment]
@pixelastic @redox @borisschapira thank you very much for your help! I wrapped the gem in a `group :jekyll_plugins` and it's working now! The search is really great and I'm looking forward to using it on our Jekyll site. I was looking at different alternatives but none of them compares to Algolia.
